language: node_js
node_js:
   -"4.2.3"
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
  go: 
 - 1.3.3
 - 1.4.2
 - 1.5.1
 before_script:
      - npm install grunt-cli -g
 install:
 npm install
  - make 
 script:
 - "./hello world"
 - go test -v ./...
 -npm test
 after_failure:
    - email
