
language: node_js
node_js:
  - "4.2.3"
before_script:
  - npm install grunt-cli -g
install: npm install
language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

language: c

install:
    - make 

    - "./hello world"

after_failure:
    - email

language: go
go: 
 - 1.3.3
 - 1.4.2
 - 1.5.1
 - release
 - tip

script:
 - go test -v ./...
  - "./hello world"
 -npm test
 -ant test
