
language: node_js
node_js:
  - "4.2.3"
before_script:
  - npm install grunt-cli -g
  -sudo apt-get install eclipse-pde
install: npm install
 - make 
 - "./hello world"
script:
 - go test -v ./...
  - "./hello world"
 -npm test
 -ant test
 
after_failure:
    - email
