
language: node_js
node_js:
  - "4.2.3"
  java:
  - oraclejdk7
  - openjdk7
  - openjdk6
  C:
  go: 
 - 1.3.3
 - 1.4.2
 - 1.5.1
 - release
 - tip

before_script:
  - npm install grunt-cli -g
install: npm install
 - make 
 - "./hello world"
script:
 - go test -v ./...
  - "./hello world"
 -npm test
 -ant test
 
after_failure:
    - email
